### PR TITLE
Upgrade BusyBox image with ps

### PR DESCRIPTION
**Pull request by rspreafico**
This PR reverts back to BusyBox as opposed to Alpine Linux due to issues highlighted in [a previous PR](https://github.com/bgruening/docker-busybox-bash/pull/2). It still allows to add `procps`' `ps` for Nextflow compatibility. 

```
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
bgruening/busybox-bash    0.2                 64a442f03c83        11 minutes ago      6.27MB
gliderlabs/alpine         3.6                 40b6e22d66ca        2 months ago        3.97MB
ubuntu                    16.04               747cb2d60bbe        3 months ago        122MB
bgruening/busybox-bash    0.1                 3d974f51245c        21 months ago       6.73MB
progrium/busybox          latest              05cb04a8038f        2 years ago         4.79MB
```

### CODE REVIEW

**Comment by rspreafico** [comment]
ping @pditommaso

**Comment by bgruening** [comment]
I discussed this with @pditommaso during the conference. Lets see if we find a solution that does not involve the gnu `ps` version.

**Comment by pditommaso** [comment]
To recap, nextflow uses the command the following command to retrieve cpu and memory usage information: 

```
ps -o pid= -o state= -o pcpu= -o pmem= -o vsz= -o rss=
```

The `ps` version included in the base base image used by biocontainers does not recognise the `state`, `pcpu` and `pmem` attributes. I think that adding the `ps` package have no negative side effects and make biocontainers more interoperable with other linux distributions. 

Said that I'm also investigating [other alternatives](https://github.com/nextflow-io/nextflow/issues/499#issuecomment-364762366).

**Comment by rspreafico** [comment]
Thanks guys! Great news! Looking forward to this.

**Comment by bgruening** [comment]
Closing, this is working now for NF users afaik :)

**Pull request closed without merging**
